[package]
name = "android-bootimg-cli"
version.workspace = true
edition.workspace = true

[dependencies]
android-bootimg = { workspace = true }
memmap2 = { workspace = true }
anyhow = { workspace = true }
paste = { workspace = true }
